name: ccpnmrV2
channels:
  - defaults
dependencies:
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - decorator
  - enum34
  - idna
  - intel-openmp
  - ipaddress
#  - libcxx
#  - libcxxabi
  - libedit
  - libffi
#  - libgfortran
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nose
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - python=2.7
  - python-dateutil
#  - python.app
  - pytz
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - urllib3
  - wheel
  - zlib
  - pip:
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
