# Create a conda env with the following command from a bash shell
# conda env create -f environment_MacOS.yml

name: <NAME INSERTED FROM internal/scripts/version.sh>
channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - decorator=4.4.1
  - enum34=1.1.6
  - freetype=2.9.1
  - idna=2.8
  - intel-openmp=2019.4
  - ipaddress=1.0.23
  - jpeg=9b
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libtiff=4.1.0
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - nose=1.3.7
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openssl=1.1.1g
  - pandas=0.24.2
  - pillow=6.2.1
  - pip=19.2.3
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=2.7.15             # must be this to stop crash on 10.14.6
  - python-dateutil=2.8.1
  - python.app=2
  - pytz=2019.3
  - readline=7.0
  - requests=2.22.0
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - tk=8.6.8
  - urllib3=1.24.2
  - wheel=0.33.6
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
