name: ccpnmrV2
channels:
  - defaults
dependencies:
  - asn1crypto
  - blas
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - cryptography
  - decorator
  - enum34
  - idna
  - intel-openmp
  - ipaddress
#  - libcxx
#  - libcxxabi
  - libedit
  - libffi
#  - libgfortran
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nose
  - numpy
  - numpy-base
  - openssl
  - pandas
  - pip
  - pycparser
  - pyopenssl
  - pysocks
  - python=2.7
  - python-dateutil
#  - python.app
  - pytz
  - readline
  - requests
  - setuptools
  - six
  - sqlite
  - tk
  - urllib3
  - wheel
  - zlib
  - pip:
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5

#name: ccpnmrV2
#channels:
#  - conda-forge
#  - smithsp
#  - defaults
#dependencies:
#  - _libgcc_mutex=0.1
#  - asn1crypto=1.3.0
#  - blas=1.0
#  - ca-certificates=2019.11.28
#  - certifi=2019.11.28
#  - cffi=1.13.2
#  - chardet=3.0.4
#  - cryptography=2.8
#  - decorator=4.4.1
#  - enum34=1.1.6
#  - fontconfig=2.13.1
#  - freetype=2.10.0
#  - icu=64.2
#  - idna=2.8
#  - intel-openmp=2020.0
#  - ipaddress=1.0.23
#  - libedit=3.1.20181209
#  - libffi=3.2.1
#  - libgcc-ng=9.1.0
#  - libgfortran-ng=7.3.0
#  - libiconv=1.15
#  - libpng=1.6.37
#  - libstdcxx-ng=9.1.0
#  - libuuid=2.32.1
#  - libxml2=2.9.10
#  - mkl=2020.0
#  - mkl-service=2.3.0
#  - mkl_fft=1.0.15
#  - mkl_random=1.1.0
#  - ncurses=6.1
#  - nose=1.3.7
#  - numpy=1.16.6
#  - numpy-base=1.16.6
#  - openssl=1.1.1d
#  - pandas=0.24.2
#  - pip=19.3.1
#  - pycparser=2.19
#  - pyopenssl=19.0.0
#  - pysocks=1.7.1
#  - python=2.7.17
#  - python-dateutil=2.8.1
#  - pytz=2019.3
#  - readline=7.0
#  - requests=2.22.0
#  - setuptools=44.0.0
#  - six=1.13.0
#  - sqlite=3.31.1
#  - tk=8.6.9
#  - urllib3=1.25.7
#  - wheel=0.33.6
#  - xz=5.2.4
#  - zlib=1.2.11
#  - pip:
#    - pyopengl==3.1.5
#    - pyopengl-accelerate==3.1.5
#prefix: /home/ccpn/miniconda3/envs/ccpnmrV2

# tk came from smithsp -think this was a build against freetype/fontconfig