name: conda-env-2.5.0
channels:
  - defaults
dependencies:
  - asn1crypto=1.3.0
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - cryptography=2.8
  - enum34=1.1.6
  - freeglut=3.0.0
  - icc_rt=2019.0.0
  - idna=2.8
  - intel-fortran_win-64=2019.0.0
  - intel-openmp=2019.4
  - ipaddress=1.0.23
  - m2w64-bzip2=1.0.6
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-tcl=8.6.5
  - m2w64-tk=8.6.5
  - m2w64-zlib=1.2.8
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - msys2-conda-epoch=20160418
  - nose=1.3.7
  - numpy=1.16.5
  - numpy-base=1.16.5
  - openssl=1.1.1d
  - pandas=0.24.2
  - pip=19.3.1
  - pthread-stubs=0.3
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=2.7.17
  - python-dateutil=2.8.1
  - pytz=2019.3
  - requests=2.22.0
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - urllib3=1.25.7
  - vc=9
  - vs2008_runtime=9.00.30729.1
  - wheel=0.33.6
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - pip:
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
